In [1]:
import numpy as np

In [2]:
arr1 = np.array([6,2,-7,2,8,-2,1])

In [3]:
arr2 = np.array([[1,3,5],[2,4,6]])

In [14]:
print(arr1.ndim)
print(arr2.ndim)
print(arr1.shape)
print(arr2.shape)
print(arr1.size)
print(arr2.size)
print(arr1.dtype)
print(arr2.dtype)

1
2
(7,)
(2, 3)
7
6
int32
int32


In [17]:
arr_all_0=np.zeros(6)
print(arr_all_0)

[0. 0. 0. 0. 0. 0.]


In [18]:
arr_all_1 = np.ones(6)
arr_all_1

array([1., 1., 1., 1., 1., 1.])

In [20]:
arr_even=np.arange(10,21,2)
arr_even

array([10, 12, 14, 16, 18, 20])

# 第二个部分

In [22]:
arr1=np.array([1,3,2,4,9])
arr1

array([1, 3, 2, 4, 9])

In [23]:
arr2=np.ones(5)
arr2

array([1., 1., 1., 1., 1.])

In [24]:
arr3=np.zeros(3)
arr3

array([0., 0., 0.])

In [26]:
arr4 = np.concatenate([arr1,arr2,arr3])
arr4

array([1., 3., 2., 4., 9., 1., 1., 1., 1., 1., 0., 0., 0.])

In [27]:
arr1.sort()
arr1

array([1, 2, 3, 4, 9])

In [28]:
print(arr1[2])
print(arr1[-3])

3
3


In [29]:
arr1[1:4]

array([2, 3, 4])

In [30]:
arr1 +arr2

array([ 2.,  3.,  4.,  5., 10.])

In [31]:
arr1 * (-5)

array([ -5, -10, -15, -20, -45])

In [33]:
print(arr1.max())
print(arr1.min())
print(arr1.sum())
print(arr1.mean())

9
1
19
3.8


In [34]:
arr1 >1

array([False,  True,  True,  True,  True])

In [35]:
arr1 <3

array([ True,  True, False, False, False])

In [38]:
arr1 >1

array([False,  True,  True,  True,  True])

In [39]:
arr1 < 3

array([ True,  True, False, False, False])

In [45]:
print(arr1[(arr1 > 1)  & (arr1 < 3)])
print(arr1)

[2]
[1 2 3 4 9]


In [ ]:
arr1[(arr1 > 1)  | (arr1 < 3)]